### ISSUE TITLE
make factories three factories, one for every view

### ISSUE THREAD

**Issue by lrpina** [lrpina/FamilySleep#37]

**Comment by CSONG09** [comment]
Added 3 factories:
sleepFamDailyDataFactory
sleepFamWeeklyDataFactory
sleepWeeklyDataFactory

**Comment by CSONG09** [comment]
Actually didn't work

Error: [$injector:unpr] Unknown provider: sleepFamDailyDataFactoryProvider <- sleepFamDailyDataFactory <- tractdbdata

**Comment by lrpina** [comment]
Hi Clarissa,

Had some family stuff going on and couldn't work on this. I'm flying back today, I'll get to this tonight!

**Comment by CSONG09** [comment]
No worries! I got it to work, I forgot to add the factories to index.html. I will close it :)

Best,
Clarissa

Sent from my iPhone

On Apr 24, 2017, at 4:20 PM, lrpina <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Clarissa,

Had some family stuff going on and couldn't work on this. I'm flying back today, I'll get to this tonight!

**Comment by lrpina** [comment]
Next time I will show you how to use yeoman for creating new files in
angular. It saves a lot of time!

But I'm glad you figured it out, it means you're understanding how things
are working.
